linters:
  enable:
    - gosimple
    - structcheck
    - varcheck
    - errcheck
    - staticcheck
    - ineffassign
    - deadcode
    - typecheck
    - govet
    - unused
    - scopelint
    - prealloc
    - misspell
    - unconvert
  disable:
    - goimports