sudo: false
dist: bionic
language: go

go:
  - 1.12.x

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.16.0
  - go get -t ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - golangci-lint run

after_success:
  - go tool cover -func coverage.out | grep -P '\s([0-5]\d|[0-9])..%'
  - bash <(curl -s https://codecov.io/bash)